engines:
  eslint:
    enabled: true
#    channel: "eslint-2"
#    config:
#        config: .eslintrc
  fixme:
    enabled: true


ratings:
  paths:
  - "**.js"

exclude_paths:
- "client/plugins/**/*"
- "client/imports/test/**/*"
